# Generated by Django 3.2.6 on 2021-08-18 05:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='分类')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='电影标题')),
                ('download_url', models.CharField(default='', max_length=300, verbose_name='下载地址')),
                ('movie_file', models.FileField(default='videos/default.mp4', max_length=200, upload_to='videos/%Y/%m', verbose_name='视频文件')),
                ('info', models.TextField(default='', verbose_name='电影简介')),
                ('logo', models.ImageField(default='image/default.png', upload_to='banner/%Y/%m', verbose_name='封面')),
                ('star', models.IntegerField(verbose_name='星级')),
                ('play_nums', models.IntegerField(verbose_name='播放量')),
                ('comment_nums', models.IntegerField(verbose_name='评论数')),
                ('area', models.CharField(max_length=200, verbose_name='上映地区')),
                ('release_time', models.DateField(default=datetime.datetime.now, verbose_name='上映时间')),
                ('length', models.CharField(max_length=200, verbose_name='时长')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '电影信息',
                'verbose_name_plural': '电影信息',
            },
        ),
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='电影标题')),
                ('logo', models.ImageField(default='image/default.png', upload_to='banner/%Y/%m', verbose_name='封面')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '上映预告',
                'verbose_name_plural': '上映预告',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='MovieCol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.movie', verbose_name='电影')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='tag',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='film.tag', verbose_name='标签'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='评论详情')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.movie', verbose_name='电影')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户评论',
                'verbose_name_plural': '用户评论',
            },
        ),
    ]
