# Generated by Django 3.2.6 on 2021-08-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='logo',
            field=models.ImageField(default='image/default.png', upload_to='media/image/banner/%Y/%m', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_file',
            field=models.FileField(default='videos/default.mp4', max_length=200, upload_to='video/videos/%Y/%m', verbose_name='视频文件'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tag',
        ),
        migrations.AddField(
            model_name='movie',
            name='tag',
            field=models.ManyToManyField(default='', to='film.Tag', verbose_name='标签'),
        ),
    ]
