# Generated by Django 3.2.6 on 2021-08-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_auto_20210823_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='download_url',
        ),
    ]
