# Generated by Django 3.2.6 on 2021-08-30 06:52

from django.db import migrations, models
import film.models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_remove_movie_download_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='comment_nums',
            field=models.IntegerField(blank=True, default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_file',
            field=models.FileField(default='videos/default.mp4', max_length=200, upload_to=film.models.upload_to, verbose_name='视频文件'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='play_nums',
            field=models.IntegerField(blank=True, default=0, verbose_name='播放量'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='star',
            field=models.IntegerField(blank=True, default=3, verbose_name='星级'),
        ),
    ]
