weather_table = {'晴': ' wi-day-sunny ',
                 '少云': ' wi-day-cloudy ',
                 '晴间多云': ' wi-day-sunny-overcast ',
                 '多云': ' wi-day-cloudy ',
                 '阴': ' wi-cloudy ',
                 '有风': ' wi-windy ',
                 '平静': ' wi-windy ',
                 '微风': ' wi-windy ',
                 '和风': ' wi-windy ',
                 '清风': ' wi-windy ',
                 '强风/劲风': ' wi-strong-wind ',
                 '疾风': ' wi-strong-wind ',
                 '大风': ' wi-strong-wind ',
                 '烈风': ' wi-strong-wind ',
                 '风暴': ' wi-tornado ',
                 '狂爆风': ' wi-tornado ',
                 '飓风': ' wi-tornado ',
                 '热带风暴': ' wi-tornado ',
                 '霾': ' wi-fog ',
                 '中度霾': ' wi-fog ',
                 '重度霾': ' wi-fog ',
                 '严重霾': ' wi-fog ',
                 '阵雨': ' wi-showers ',
                 '雷阵雨': ' wi-storm-showers ',
                 '雷阵雨并伴有冰雹': ' wi-storm-showers ',
                 '小雨': ' wi-sprinkle ',
                 '中雨': ' wi-sprinkle ',
                 '大雨': ' wi-rain ',
                 '暴雨': ' wi-rain ',
                 '大暴雨': ' wi-rain ',
                 '特大暴雨': ' wi-rain ',
                 '强阵雨': ' wi-rain-mix ',
                 '强雷阵雨': ' wi-storm-showers ',
                 '极端降雨': ' wi-rain ',
                 '毛毛雨/细雨': ' wi-sprinkles ',
                 '雨': ' wi-sprinkle ',
                 '小雨-中雨': ' wi-rain ',
                 '中雨-大雨': ' wi-rain ',
                 '大雨-暴雨': ' wi-rain ',
                 '暴雨-大暴雨': ' wi-rain ',
                 '大暴雨-特大暴雨': ' wi-rain ',
                 '雨雪天气': ' wi-rain-mix ',
                 '雨夹雪': ' wi-rain-mix ',
                 '阵雨夹雪': ' wi-rain-mix ',
                 '冻雨': ' wi-rain-mix ',
                 '雪': ' wi-snow ',
                 '阵雪': ' wi-showers ',
                 '小雪': ' wi-snow ',
                 '中雪': ' wi-snow ',
                 '大雪': ' wi-snow ',
                 '暴雪': ' wi-snow ',
                 '小雪-中雪': ' wi-snow ',
                 '中雪-大雪': ' wi-snow ',
                 '大雪-暴雪': ' wi-snow ',
                 '浮尘': ' wi-fog ',
                 '扬沙': ' wi-fog ',
                 '沙尘暴': ' wi-fog ',
                 '强沙尘暴': ' wi-fog ',
                 '龙卷风': ' wi-tornado ',
                 '雾': ' wi-fog ',
                 '浓雾': ' wi-fog ',
                 '强浓雾': ' wi-fog ',
                 '轻雾': ' wi-fog ',
                 '大雾': ' wi-fog ',
                 '特强浓雾': ' wi-fog ',
                 '热': '',
                 '冷': '',
                 '未知': ''}
wind_direct = {
    '无风向': '',

    '东北': 'wi-wind-north-east',

    '东': 'wi-wind-east',

    '东南': 'wi-wind-south-east',

    '南': 'wi-wind-south',

    '西南': 'wi-wind-south-west',

    '西': 'wi-wind-west',

    '西北': 'wi-wind-north-west',

    '北': 'wi-wind-north',

    '旋转不定': '',
}
