# Generated by Django 3.2.5 on 2021-07-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempHum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='温度')),
                ('humidity', models.FloatField(verbose_name='湿度')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
        ),
    ]
