# Generated by Django 3.2.5 on 2021-07-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='待办事项')),
                ('date', models.DateField(verbose_name='事项日期')),
                ('period', models.SmallIntegerField(default=0, help_text='每n天执行的事项，如每月还款', verbose_name='事项周期')),
                ('fix_day', models.BooleanField(default=True, help_text='例如：事项是16日执行，此后每月固定16日执行此事项', verbose_name='固定日期')),
            ],
        ),
    ]
