# Generated by Django 3.2.5 on 2021-07-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0002_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='fix_day',
            field=models.BooleanField(default=False, help_text='例如：事项是16日执行，此后每月固定16日执行此事项', verbose_name='固定日期'),
        ),
    ]
