# Generated by Django 3.2.5 on 2021-07-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0003_alter_todo_fix_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(help_text='最多16个字符', max_length=16, verbose_name='待办事项'),
        ),
    ]
