# Generated by Django 3.2.5 on 2021-07-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0004_alter_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='fix_day',
            field=models.BooleanField(default=False, help_text='例如：事项是16日执行，此后每月固定16日执行此事项.优先级大于事项周期。', verbose_name='固定日期'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='period',
            field=models.SmallIntegerField(default=0, help_text='每n天执行的事项', verbose_name='事项周期'),
        ),
    ]
